-- ============================================================
-- 課指組器材與場地預約平台 - D1 SQLite Schema (27 Tables)
-- 根據 114 SA 範本 1.2 資料庫設計
-- Prompt7 優化版：修正資料型態一致性、正規化
-- ============================================================

-- 1. User
CREATE TABLE IF NOT EXISTS User (
  USR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USR_EMAIL TEXT NOT NULL UNIQUE,
  USR_NAME TEXT NOT NULL,
  USR_PHONE TEXT DEFAULT NULL,
  USR_ROLE TEXT NOT NULL DEFAULT 'student',
  USR_IS_ADMIN INTEGER NOT NULL DEFAULT 0,
  USR_SUSPENDED INTEGER NOT NULL DEFAULT 0,
  USR_EXPIRE_DATE TEXT DEFAULT NULL,
  USR_PASSWORD_HASH TEXT DEFAULT NULL,
  USR_AVATAR TEXT DEFAULT NULL,
  USR_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 2. Unit
CREATE TABLE IF NOT EXISTS Unit (
  UNIT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  UNIT_NAME TEXT NOT NULL UNIQUE,
  UNIT_TYPE INTEGER NOT NULL,
  UNIT_CONTACT_USR INTEGER NOT NULL REFERENCES User(USR_ID),
  UNIT_ACTIVE INTEGER NOT NULL DEFAULT 1,
  UNIT_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 3. UnitMember
CREATE TABLE IF NOT EXISTS UnitMember (
  UM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  UM_UNIT_ID INTEGER NOT NULL REFERENCES Unit(UNIT_ID),
  UM_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  UM_JOINED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  UM_ACTIVE INTEGER NOT NULL DEFAULT 1,
  UNIQUE(UM_UNIT_ID, UM_USR_ID)
);

-- 4. UnitViolationPoint
CREATE TABLE IF NOT EXISTS UnitViolationPoint (
  UVP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  UVP_UNIT_ID INTEGER NOT NULL UNIQUE REFERENCES Unit(UNIT_ID),
  UVP_POINT INTEGER NOT NULL DEFAULT 0,
  UVP_SUSPENDED INTEGER NOT NULL DEFAULT 0,
  UVP_UPDATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 5. EquipmentCertType
CREATE TABLE IF NOT EXISTS EquipmentCertType (
  ECT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ECT_NAME TEXT NOT NULL UNIQUE,
  ECT_DESC TEXT DEFAULT NULL
);

-- 6. EquipmentCert
CREATE TABLE IF NOT EXISTS EquipmentCert (
  EC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EC_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  EC_TYPE_ID INTEGER NOT NULL REFERENCES EquipmentCertType(ECT_ID),
  EC_STATUS INTEGER NOT NULL DEFAULT 0,
  EC_GRANTED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  EC_REVOKED_AT TEXT DEFAULT NULL,
  EC_ADMIN_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  UNIQUE(EC_USR_ID, EC_TYPE_ID)
);

-- 7. Facility
CREATE TABLE IF NOT EXISTS Facility (
  FAC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FAC_NAME TEXT NOT NULL,
  FAC_TYPE INTEGER NOT NULL,
  FAC_BUILDING TEXT NOT NULL,
  FAC_FLOOR INTEGER NOT NULL,
  FAC_CAPACITY INTEGER NOT NULL,
  FAC_GIS_LAT REAL DEFAULT NULL,
  FAC_GIS_LNG REAL DEFAULT NULL,
  FAC_STATUS INTEGER NOT NULL DEFAULT 0,
  FAC_DESC TEXT DEFAULT NULL,
  FAC_ACTIVE INTEGER NOT NULL DEFAULT 1
);

-- 8. FacilityMaintenanceLog
CREATE TABLE IF NOT EXISTS FacilityMaintenanceLog (
  FML_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FML_FAC_ID INTEGER NOT NULL REFERENCES Facility(FAC_ID),
  FML_START_DATE TEXT NOT NULL,
  FML_END_DATE TEXT DEFAULT NULL,
  FML_ACTUAL_END TEXT DEFAULT NULL,
  FML_NOTE TEXT DEFAULT NULL,
  FML_ADMIN_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  FML_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 9. Equipment
CREATE TABLE IF NOT EXISTS Equipment (
  EQ_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EQ_NAME TEXT NOT NULL,
  EQ_TOTAL INTEGER NOT NULL,
  EQ_PHYSICAL_CODE TEXT DEFAULT NULL,
  EQ_AVAILABLE INTEGER NOT NULL,
  EQ_MAX_PER_LOAN INTEGER NOT NULL,
  EQ_CERT_TYPE_ID INTEGER DEFAULT NULL REFERENCES EquipmentCertType(ECT_ID),
  EQ_DESC TEXT DEFAULT NULL,
  EQ_ACTIVE INTEGER NOT NULL DEFAULT 1
);

-- 10. ActivityApplication
CREATE TABLE IF NOT EXISTS ActivityApplication (
  AA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  AA_SERIAL_NO TEXT NOT NULL UNIQUE,
  AA_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  AA_UNIT_ID INTEGER NOT NULL REFERENCES Unit(UNIT_ID),
  AA_ACTIVITY_NAME TEXT NOT NULL,
  AA_START_DATETIME TEXT NOT NULL,
  AA_END_DATETIME TEXT NOT NULL,
  AA_HEADCOUNT INTEGER NOT NULL,
  AA_DESCRIPTION TEXT DEFAULT NULL,
  AA_CONTACT_NAME TEXT DEFAULT NULL,
  AA_CONTACT_PHONE TEXT DEFAULT NULL,
  AA_CONTACT_EMAIL TEXT DEFAULT NULL,
  AA_THEMES TEXT DEFAULT NULL,
  AA_HAS_ALCOHOL INTEGER DEFAULT 0,
  AA_HAS_FIRE INTEGER DEFAULT 0,
  AA_HAS_BOOTH INTEGER DEFAULT 0,
  AA_STATUS INTEGER NOT NULL DEFAULT 0,
  AA_ADMIN_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  AA_ADMIN_NOTE TEXT DEFAULT NULL,
  AA_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  AA_REVIEWED_AT TEXT DEFAULT NULL
);

-- 11. VenueBooking
CREATE TABLE IF NOT EXISTS VenueBooking (
  VB_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  VB_AA_ID INTEGER NOT NULL REFERENCES ActivityApplication(AA_ID),
  VB_FAC_ID INTEGER NOT NULL REFERENCES Facility(FAC_ID),
  VB_UNIT_ID INTEGER NOT NULL REFERENCES Unit(UNIT_ID),
  VB_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  VB_START_DATETIME TEXT NOT NULL,
  VB_END_DATETIME TEXT NOT NULL,
  VB_PURPOSE TEXT NOT NULL,
  VB_HEADCOUNT INTEGER NOT NULL,
  VB_BOOKING_TYPE INTEGER NOT NULL,
  VB_RECURRENCE_ID INTEGER DEFAULT NULL,
  VB_STATUS INTEGER NOT NULL DEFAULT 0,
  VB_ADMIN_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  VB_REJECT_REASON TEXT DEFAULT NULL,
  VB_RETURN_AT TEXT DEFAULT NULL,
  VB_RETURN_NOTE TEXT DEFAULT NULL,
  VB_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_vb_conflict ON VenueBooking(VB_FAC_ID, VB_STATUS, VB_START_DATETIME, VB_END_DATETIME);

-- 12. VenueBookingRecurrence
CREATE TABLE IF NOT EXISTS VenueBookingRecurrence (
  VBR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  VBR_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  VBR_UNIT_ID INTEGER NOT NULL REFERENCES Unit(UNIT_ID),
  VBR_FAC_ID INTEGER NOT NULL REFERENCES Facility(FAC_ID),
  VBR_AA_ID INTEGER NOT NULL REFERENCES ActivityApplication(AA_ID),
  VBR_DAY_OF_WEEK INTEGER NOT NULL,
  VBR_START_DATE TEXT NOT NULL,
  VBR_END_DATE TEXT NOT NULL,
  VBR_TIME_START TEXT NOT NULL,
  VBR_TIME_END TEXT NOT NULL,
  VBR_STATUS INTEGER NOT NULL DEFAULT 0,
  VBR_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 13. EquipmentLoan
CREATE TABLE IF NOT EXISTS EquipmentLoan (
  EL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EL_AA_ID INTEGER NOT NULL REFERENCES ActivityApplication(AA_ID),
  EL_UNIT_ID INTEGER NOT NULL REFERENCES Unit(UNIT_ID),
  EL_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  EL_BORROW_START TEXT NOT NULL,
  EL_RETURN_DUE TEXT NOT NULL,
  EL_USE_LOCATION TEXT NOT NULL,
  EL_PURPOSE TEXT NOT NULL,
  EL_LOAN_TYPE INTEGER NOT NULL,
  EL_RECURRENCE_ID INTEGER DEFAULT NULL,
  EL_STATUS INTEGER NOT NULL DEFAULT 0,
  EL_ADMIN_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  EL_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 14. EquipmentLoanDetail
CREATE TABLE IF NOT EXISTS EquipmentLoanDetail (
  ELD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ELD_EL_ID INTEGER NOT NULL REFERENCES EquipmentLoan(EL_ID),
  ELD_EQ_ID INTEGER NOT NULL REFERENCES Equipment(EQ_ID),
  ELD_QUANTITY INTEGER NOT NULL,
  ELD_APPROVED_QTY INTEGER DEFAULT NULL,
  ELD_STATUS INTEGER NOT NULL DEFAULT 0,
  ELD_PICKUP_AT TEXT DEFAULT NULL,
  ELD_RETURN_AT TEXT DEFAULT NULL,
  ELD_RETURN_NOTE TEXT DEFAULT NULL,
  UNIQUE(ELD_EL_ID, ELD_EQ_ID)
);

-- 15. EquipmentLoanRecurrence
CREATE TABLE IF NOT EXISTS EquipmentLoanRecurrence (
  ELR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ELR_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  ELR_UNIT_ID INTEGER NOT NULL REFERENCES Unit(UNIT_ID),
  ELR_AA_ID INTEGER NOT NULL REFERENCES ActivityApplication(AA_ID),
  ELR_DAY_OF_WEEK INTEGER NOT NULL,
  ELR_START_DATE TEXT NOT NULL,
  ELR_END_DATE TEXT NOT NULL,
  ELR_STATUS INTEGER NOT NULL DEFAULT 0,
  ELR_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 16. EquipmentLoanRecurrenceDetail
CREATE TABLE IF NOT EXISTS EquipmentLoanRecurrenceDetail (
  ELRD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ELRD_ELR_ID INTEGER NOT NULL REFERENCES EquipmentLoanRecurrence(ELR_ID),
  ELRD_EQ_ID INTEGER NOT NULL REFERENCES Equipment(EQ_ID),
  ELRD_QUANTITY INTEGER NOT NULL,
  UNIQUE(ELRD_ELR_ID, ELRD_EQ_ID)
);

-- 17. ConflictNegotiation
CREATE TABLE IF NOT EXISTS ConflictNegotiation (
  CN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CN_VB_ID_A INTEGER NOT NULL REFERENCES VenueBooking(VB_ID),
  CN_VB_ID_B INTEGER NOT NULL REFERENCES VenueBooking(VB_ID),
  CN_STATUS INTEGER NOT NULL DEFAULT 0,
  CN_RESOLVED_BY INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  CN_OPENED_AT TEXT DEFAULT NULL,
  CN_CLOSED_AT TEXT DEFAULT NULL,
  CN_DELETE_AT TEXT DEFAULT NULL,
  CN_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 18. CoordinationMessage
CREATE TABLE IF NOT EXISTS CoordinationMessage (
  CM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CM_CN_ID INTEGER NOT NULL REFERENCES ConflictNegotiation(CN_ID),
  CM_SENDER_ROLE INTEGER NOT NULL,
  CM_CONTENT TEXT NOT NULL,
  CM_SENT_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 19. VenueCoordination (場協大會登記)
CREATE TABLE IF NOT EXISTS VenueCoordination (
  VC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  VC_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  VC_UNIT_ID INTEGER NOT NULL REFERENCES Unit(UNIT_ID),
  VC_FAC_ID INTEGER NOT NULL REFERENCES Facility(FAC_ID),
  VC_DAY_OF_WEEK INTEGER NOT NULL,
  VC_TIME_START TEXT NOT NULL,
  VC_TIME_END TEXT NOT NULL,
  VC_PURPOSE TEXT DEFAULT NULL,
  VC_STATUS INTEGER NOT NULL DEFAULT 0,
  VC_SEMESTER TEXT NOT NULL,
  VC_ADMIN_NOTE TEXT DEFAULT NULL,
  VC_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 20. RepairRequest
CREATE TABLE IF NOT EXISTS RepairRequest (
  RR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  RR_FAC_ID INTEGER NOT NULL REFERENCES Facility(FAC_ID),
  RR_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  RR_DESCRIPTION TEXT NOT NULL,
  RR_STATUS INTEGER NOT NULL DEFAULT 0,
  RR_ADMIN_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  RR_ADMIN_NOTE TEXT DEFAULT NULL,
  RR_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  RR_RESOLVED_AT TEXT DEFAULT NULL
);

-- 21. RepairRequestPhoto
CREATE TABLE IF NOT EXISTS RepairRequestPhoto (
  RRP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  RRP_RR_ID INTEGER NOT NULL REFERENCES RepairRequest(RR_ID),
  RRP_URL TEXT NOT NULL,
  RRP_UPLOADED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 22. AppealCase
CREATE TABLE IF NOT EXISTS AppealCase (
  AC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  AC_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  AC_TYPE INTEGER NOT NULL,
  AC_REF_LOG_ID INTEGER DEFAULT NULL,
  AC_REASON TEXT NOT NULL,
  AC_EVIDENCE TEXT DEFAULT NULL,
  AC_STATUS INTEGER NOT NULL DEFAULT 0,
  AC_ADMIN_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  AC_ADMIN_NOTE TEXT DEFAULT NULL,
  AC_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  AC_REVIEWED_AT TEXT DEFAULT NULL
);

-- 23. LaborServiceApplication
CREATE TABLE IF NOT EXISTS LaborServiceApplication (
  LSA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LSA_USR_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  LSA_SERVICE_TYPE TEXT NOT NULL,
  LSA_SERVICE_DATE TEXT NOT NULL,
  LSA_HOURS INTEGER NOT NULL,
  LSA_POINTS_TO_DEDUCT INTEGER NOT NULL,
  LSA_STATUS INTEGER NOT NULL DEFAULT 0,
  LSA_ADMIN_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  LSA_ADMIN_NOTE TEXT DEFAULT NULL,
  LSA_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  LSA_REVIEWED_AT TEXT DEFAULT NULL
);

-- 24. ViolationPointLog
CREATE TABLE IF NOT EXISTS ViolationPointLog (
  VPL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  VPL_TARGET_TYPE INTEGER NOT NULL,
  VPL_USR_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  VPL_UNIT_ID INTEGER DEFAULT NULL REFERENCES Unit(UNIT_ID),
  VPL_DELTA INTEGER NOT NULL,
  VPL_REASON TEXT NOT NULL,
  VPL_SOURCE INTEGER NOT NULL,
  VPL_ADMIN_ID INTEGER DEFAULT NULL REFERENCES User(USR_ID),
  VPL_REF_ID INTEGER DEFAULT NULL,
  VPL_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 25. OperationLog
CREATE TABLE IF NOT EXISTS OperationLog (
  OL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  OL_ADMIN_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  OL_OP_TYPE TEXT NOT NULL,
  OL_TARGET_TABLE TEXT NOT NULL,
  OL_TARGET_ID INTEGER NOT NULL,
  OL_NOTE TEXT DEFAULT NULL,
  OL_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 26. Announcement
CREATE TABLE IF NOT EXISTS Announcement (
  ANN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ANN_TITLE TEXT NOT NULL,
  ANN_CONTENT TEXT NOT NULL,
  ANN_START_DATE TEXT NOT NULL,
  ANN_END_DATE TEXT NOT NULL,
  ANN_ADMIN_ID INTEGER NOT NULL REFERENCES User(USR_ID),
  ANN_CREATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 27. StatsSummary
CREATE TABLE IF NOT EXISTS StatsSummary (
  SS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SS_FAC_ID INTEGER DEFAULT NULL REFERENCES Facility(FAC_ID),
  SS_EQ_ID INTEGER DEFAULT NULL REFERENCES Equipment(EQ_ID),
  SS_PERIOD TEXT NOT NULL,
  SS_BOOKING_COUNT INTEGER NOT NULL DEFAULT 0,
  SS_TOTAL_HOURS REAL NOT NULL DEFAULT 0,
  SS_UTILIZATION_RATE REAL NOT NULL DEFAULT 0,
  SS_SIMPSON_INDEX REAL DEFAULT NULL,
  SS_UPDATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);
