<?php

namespace Database\Seeders\Domain;

use App\Models\Club;
use Illuminate\Database\Seeder;

class ClubSeeder extends Seeder {
    public function run(): void {
        $clubsData = [
            ['健言社', 'academic', '學術性', 'club', 30],
            ['大千社', 'academic', '學術性', 'club', 25],
            ['天文社', 'academic', '學術性', 'club', 28],
            ['中華醫藥研習社', 'academic', '學術性', 'club', 22],
            ['國際經濟商管學生會', 'academic', '學術性', 'club', 45],
            ['占星塔羅社', 'academic', '學術性', 'club', 35],
            ['信望愛社', 'academic', '學術性', 'club', 30],
            ['淨仁社', 'academic', '學術性', 'club', 25],
            ['學園團契社', 'academic', '學術性', 'club', 40],
            ['禪學社', 'academic', '學術性', 'club', 20],
            ['聖經研究社', 'academic', '學術性', 'club', 18],
            ['教育學程學會', 'academic', '學術性', 'club', 30],
            ['福智青年社', 'academic', '學術性', 'club', 35],
            ['性別研究社', 'academic', '學術性', 'club', 28],
            ['永續影響力大使社', 'academic', '學術性', 'club', 32],
            ['創新創業社', 'academic', '學術性', 'club', 45],
            ['租稅研究社', 'academic', '學術性', 'club', 20],
            ['光鹽社', 'academic', '學術性', 'club', 22],
            ['金融投資研究社', 'academic', '學術性', 'club', 38],
            ['僑生聯誼會', 'recreation', '休閒聯誼性', 'club', 50],
            ['高中校友聯合總會', 'recreation', '休閒聯誼性', 'club', 60],
            ['轉學生聯誼會', 'recreation', '休閒聯誼性', 'club', 40],
            ['野營社', 'recreation', '休閒聯誼性', 'club', 35],
            ['魔術社', 'recreation', '休閒聯誼性', 'club', 25],
            ['棋藝社', 'recreation', '休閒聯誼性', 'club', 28],
            ['飲料調製社', 'recreation', '休閒聯誼性', 'club', 32],
            ['努瑪社', 'recreation', '休閒聯誼性', 'club', 20],
            ['國際菁英學生會', 'recreation', '休閒聯誼性', 'club', 45],
            ['桌上遊戲社', 'recreation', '休閒聯誼性', 'club', 55],
            ['電子競技社', 'recreation', '休閒聯誼性', 'club', 60],
            ['二輪社', 'recreation', '休閒聯誼性', 'club', 30],
            ['咖啡研究社', 'recreation', '休閒聯誼性', 'club', 25],
            ['韓國流行文化研究社', 'recreation', '休閒聯誼性', 'club', 38],
            ['同舟共濟服務社', 'service', '服務性', 'club', 35],
            ['醒新愛愛服務社', 'service', '服務性', 'club', 30],
            ['急救康輔社', 'service', '服務性', 'club', 28],
            ['崇德志工服務社', 'service', '服務性', 'club', 32],
            ['基層文化服務社', 'service', '服務性', 'club', 25],
            ['慈濟青年社', 'service', '服務性', 'club', 40],
            ['繪本服務學習社', 'service', '服務性', 'club', 22],
            ['勵德青少年服務社', 'service', '服務性', 'club', 20],
            ['登山社', 'sports', '體能性', 'club', 38],
            ['國術社', 'sports', '體能性', 'club', 25],
            ['跆拳道社', 'sports', '體能性', 'club', 30],
            ['柔道社', 'sports', '體能性', 'club', 22],
            ['劍道社', 'sports', '體能性', 'club', 20],
            ['擊劍社', 'sports', '體能性', 'club', 18],
            ['羽球社', 'sports', '體能性', 'club', 45],
            ['桌球社', 'sports', '體能性', 'club', 40],
            ['網球社', 'sports', '體能性', 'club', 35],
            ['射箭社', 'sports', '體能性', 'club', 25],
            ['同心救生社', 'sports', '體能性', 'club', 28],
            ['空手道社', 'sports', '體能性', 'club', 22],
            ['黑輪社', 'sports', '體能性', 'club', 30],
            ['合氣道社', 'sports', '體能性', 'club', 20],
            ['歐洲劍術社', 'sports', '體能性', 'club', 18],
            ['撞球社', 'sports', '體能性', 'club', 25],
            ['Kali武術社', 'sports', '體能性', 'club', 15],
            ['自由潛水社', 'sports', '體能性', 'club', 20],
            ['跑步社', 'sports', '體能性', 'club', 35],
            ['袋棍球社', 'sports', '體能性', 'club', 22],
            ['書法社', 'arts', '藝術性', 'club', 22],
            ['攝影社', 'arts', '藝術性', 'club', 45],
            ['熱舞社', 'arts', '藝術性', 'club', 60],
            ['戲劇社', 'arts', '藝術性', 'club', 35],
            ['國際標準舞蹈社', 'arts', '藝術性', 'club', 25],
            ['廣播演藝社', 'arts', '藝術性', 'club', 28],
            ['動漫電玩研習社', 'arts', '藝術性', 'club', 55],
            ['影片創作社', 'arts', '藝術性', 'club', 30],
            ['弓道社', 'arts', '藝術性', 'club', 22],
            ['光火藝術社', 'arts', '藝術性', 'club', 18],
            ['民俗體育社', 'arts', '藝術性', 'club', 20],
            ['生活花藝設計社', 'arts', '藝術性', 'club', 25],
            ['國樂社', 'music', '音樂性', 'club', 35],
            ['管弦樂社', 'music', '音樂性', 'club', 40],
            ['民謠吉他社', 'music', '音樂性', 'club', 45],
            ['搖滾音樂研究社', 'music', '音樂性', 'club', 30],
            ['鋼琴社', 'music', '音樂性', 'club', 28],
            ['數位音樂創作研習社', 'music', '音樂性', 'club', 25],
            ['烏克麗麗社', 'music', '音樂性', 'club', 32],
            ['嘻哈文化社', 'music', '音樂性', 'club', 38],
            ['爵士鋼琴社', 'music', '音樂性', 'club', 22],
        ];

        foreach ($clubsData as $club) {
            Club::updateOrCreate([
                'name' => $club[0],
                'type' => $club[3],
            ], [
                'category' => $club[1],
                'category_label' => $club[2],
                'description' => $club[0] . ' - 輔仁大學114學年度',
                'member_count' => $club[4],
                'is_active' => true,
            ]);
        }

        $associationsData = [
            ['學生會', 'student_gov', '學生自治', 'association', 0, '001'],
            ['學生議會', 'student_gov', '學生自治', 'association', 0, '002'],
            ['學生法庭', 'student_gov', '學生自治', 'association', 0, '-'],
            ['文學院代會', 'liberal_arts', '院代會', 'association', 0, '112'],
            ['中文系學會', 'liberal_arts', '系學會', 'association', 120, '008'],
            ['歷史系學會', 'liberal_arts', '系學會', 'association', 85, '009'],
            ['哲學系學會', 'liberal_arts', '系學會', 'association', 70, '010'],
            ['社創學程學會', 'liberal_arts', '學程學會', 'association', 30, '301'],
            ['藝術院代會', 'arts_college', '院代會', 'association', 0, '113'],
            ['音樂系學會', 'arts_college', '系學會', 'association', 45, '015'],
            ['應美系學會', 'arts_college', '系學會', 'association', 50, '016'],
            ['景觀系學會', 'arts_college', '系學會', 'association', 40, '105'],
            ['傳播院代會', 'communications', '院代會', 'association', 0, '110'],
            ['影傳系學會', 'communications', '系學會', 'association', 75, '130'],
            ['新傳系學會', 'communications', '系學會', 'association', 85, '133'],
            ['廣告系學會', 'communications', '系學會', 'association', 80, '134'],
            ['教運院代會', 'education', '院代會', 'association', 0, '108'],
            ['圖資系學會', 'education', '系學會', 'association', 60, '011'],
            ['體育系學會', 'education', '系學會', 'association', 55, '014'],
            ['領科學程學會', 'education', '學程學會', 'association', 30, '181'],
            ['理工院代會', 'science', '院代會', 'association', 0, '004'],
            ['數學系學會', 'science', '系學會', 'association', 65, '017'],
            ['物理系學會', 'science', '系學會', 'association', 55, '018'],
            ['化學系學會', 'science', '系學會', 'association', 50, '019'],
            ['生科系學會', 'science', '系學會', 'association', 60, '020'],
            ['電機系學會', 'science', '系學會', 'association', 90, '024'],
            ['資工系學會', 'science', '系學會', 'association', 105, '025'],
            ['醫資學程學會', 'science', '學程學會', 'association', 40, '182'],
            ['資安學程學會', 'science', '學程學會', 'association', 35, '197'],
            ['外語院代會', 'languages', '院代會', 'association', 0, '005'],
            ['英文系學會', 'languages', '系學會', 'association', 110, '026'],
            ['德語系學會', 'languages', '系學會', 'association', 35, '027'],
            ['法文系學會', 'languages', '系學會', 'association', 30, '028'],
            ['西文系學會', 'languages', '系學會', 'association', 40, '029'],
            ['日文系學會', 'languages', '系學會', 'association', 65, '030'],
            ['義文系學會', 'languages', '系學會', 'association', 25, '040'],
            ['科創學程學會', 'languages', '學程學會', 'association', 30, '302'],
            ['民生院代會', 'livelihood', '院代會', 'association', 0, '120'],
            ['兒家系學會', 'livelihood', '系學會', 'association', 60, '012'],
            ['餐旅系學會', 'livelihood', '系學會', 'association', 90, '021'],
            ['食科系學會', 'livelihood', '系學會', 'association', 70, '022'],
            ['營養系學會', 'livelihood', '系學會', 'association', 80, '145'],
            ['織品院代會', 'textiles', '院代會', 'association', 0, '187'],
            ['織品系學會', 'textiles', '系學會', 'association', 65, '023'],
            ['法律院代會', 'law', '院代會', 'association', 0, '007'],
            ['法律系學會', 'law', '系學會', 'association', 130, '034'],
            ['財法系學會', 'law', '系學會', 'association', 80, '111'],
            ['學士後法律系學會', 'law', '系學會', 'association', 50, '152'],
            ['管院代會', 'management', '院代會', 'association', 0, '006'],
            ['企管系學會', 'management', '系學會', 'association', 150, '035'],
            ['會計系學會', 'management', '系學會', 'association', 120, '036'],
            ['統資系學會', 'management', '系學會', 'association', 80, '037'],
            ['金企系學會', 'management', '系學會', 'association', 110, '038'],
            ['資管系學會', 'management', '系學會', 'association', 100, '039'],
            ['社科院代會', 'social_science', '院代會', 'association', 0, '115'],
            ['社會學會', 'social_science', '系學會', 'association', 70, '031'],
            ['社工系學會', 'social_science', '系學會', 'association', 95, '032'],
            ['經濟系學會', 'social_science', '系學會', 'association', 90, '033'],
            ['宗教系學會', 'social_science', '系學會', 'association', 50, '121'],
            ['心理系學會', 'social_science', '系學會', 'association', 90, '013'],
            ['天學學程學會', 'social_science', '學程學會', 'association', 25, '176'],
            ['醫學院代會', 'medicine', '院代會', 'association', 0, '114'],
            ['公衛系學會', 'medicine', '系學會', 'association', 80, '103'],
            ['護理系學會', 'medicine', '系學會', 'association', 125, '104'],
            ['臨心系學會', 'medicine', '系學會', 'association', 75, '122'],
            ['醫學系學會', 'medicine', '系學會', 'association', 140, '102'],
            ['職治系學會', 'medicine', '系學會', 'association', 60, '135'],
            ['呼治系學會', 'medicine', '系學會', 'association', 45, '154'],
            ['進-學代會', 'evening_div', '院代會', 'association', 0, '202'],
            ['進-中文系學會', 'evening_div', '系學會', 'association', 40, '203'],
            ['進-歷史系學會', 'evening_div', '系學會', 'association', 35, '204'],
            ['進-大傳學程學會', 'evening_div', '學程學會', 'association', 30, '206'],
            ['進-運資學程學會', 'evening_div', '學程學會', 'association', 25, '207'],
            ['進-英文系學會', 'evening_div', '系學會', 'association', 35, '208'],
            ['進-日文系學會', 'evening_div', '系學會', 'association', 30, '209'],
            ['進-法律系學會', 'evening_div', '系學會', 'association', 40, '211'],
            ['進-經濟系學會', 'evening_div', '系學會', 'association', 35, '212'],
            ['進-餐旅系學會', 'evening_div', '系學會', 'association', 45, '225'],
            ['進-應美系學會', 'evening_div', '系學會', 'association', 30, '226'],
            ['進-文創學程學會', 'evening_div', '學程學會', 'association', 25, '228'],
            ['進-運管學程學會', 'evening_div', '學程學會', 'association', 28, '230'],
            ['進-商管學程學會', 'evening_div', '學程學會', 'association', 35, '231'],
            ['進-軟創學程學會', 'evening_div', '學程學會', 'association', 22, '232'],
            ['進-長照學程學會', 'evening_div', '學程學會', 'association', 20, '233'],
            ['進-文服學程學會', 'evening_div', '學程學會', 'association', 18, '234'],
            ['進-室設學程學會', 'evening_div', '學程學會', 'association', 22, '236'],
            ['進-服飾學程學會', 'evening_div', '學程學會', 'association', 20, '237'],
        ];

        foreach ($associationsData as $association) {
            Club::updateOrCreate([
                'name' => $association[0],
                'type' => $association[3],
            ], [
                'category' => $association[1],
                'category_label' => $association[2],
                'description' => '代號：' . $association[5] . ' - 輔仁大學114學年度',
                'member_count' => $association[4],
                'is_active' => true,
            ]);
        }
    }
}
