@extends('layouts.shell')
@section('title', '活動牆')
@php $activePage = 'activity-wall'; @endphp
@section('content')
<div class="space-y-6">
<div class="flex items-center justify-between flex-wrap gap-2"><h2 class="font-bold text-fju-blue text-lg"><i class="fas fa-newspaper mr-2 text-fju-yellow"></i>動態活動牆</h2><button onclick="document.getElementById('act-modal').classList.remove('hidden')" class="btn-yellow px-4 py-2 text-sm"><i class="fas fa-plus mr-1"></i>新增活動</button></div>
<div class="flex gap-2 mb-4"><button onclick="filterAct('all')" class="act-f px-3 py-1 rounded-fju bg-fju-blue text-white text-xs" data-f="all">全部</button><button onclick="filterAct('approved')" class="act-f px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-f="approved">已核准</button><button onclick="filterAct('pending')" class="act-f px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-f="pending">待審核</button></div>
<div class="grid md:grid-cols-2 gap-4" id="act-grid"><div class="p-8 text-center text-gray-400 col-span-2"><i class="fas fa-spinner fa-spin"></i></div></div>
<div id="act-modal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center"><div class="bg-white rounded-fju-lg p-6 w-full max-w-lg mx-4"><h3 class="font-bold text-fju-blue text-lg mb-4">新增活動</h3><div class="space-y-3"><input id="a-title" placeholder="活動名稱" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm"><textarea id="a-desc" placeholder="說明" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm"></textarea><div class="grid grid-cols-2 gap-3"><input type="date" id="a-date" class="px-4 py-2 rounded-fju border border-gray-200 text-sm"><input type="number" id="a-max" placeholder="人數上限" class="px-4 py-2 rounded-fju border border-gray-200 text-sm"></div></div><div class="flex gap-2 mt-4"><button onclick="addAct()" class="flex-1 btn-yellow py-2">新增</button><button onclick="document.getElementById('act-modal').classList.add('hidden')" class="flex-1 py-2 rounded-fju border border-gray-200 text-sm text-gray-500">取消</button></div></div></div>
</div>
<script>
let allActs=[];
fetch('/api/activities').then(r=>r.json()).then(res=>{allActs=res.data;renderActs(allActs)});
function renderActs(data){document.getElementById('act-grid').innerHTML=data.map(a=>'<div class="bg-white rounded-fju-lg p-5 shadow-sm border border-gray-100 card-hover"><div class="flex items-start justify-between mb-2"><h3 class="font-bold text-fju-blue">'+a.title+'</h3><span class="px-2 py-1 rounded-fju text-xs '+(a.status==='approved'?'bg-fju-green/10 text-fju-green':'bg-fju-yellow/20 text-fju-yellow')+'">'+a.status+'</span></div><p class="text-xs text-gray-500 mb-2">'+(a.description||'')+'</p><div class="flex items-center gap-4 text-xs text-gray-400"><span><i class="fas fa-calendar mr-1"></i>'+a.event_date+'</span><span><i class="fas fa-clock mr-1"></i>'+a.start_time+'-'+a.end_time+'</span><span><i class="fas fa-users mr-1"></i>'+a.current_participants+'/'+a.max_participants+'</span></div><div class="flex gap-2 mt-3"><button onclick="registerAct('+a.id+')" class="btn-yellow px-3 py-1 text-xs">報名</button><button onclick="deleteAct('+a.id+')" class="text-fju-red text-xs px-2 py-1 rounded hover:bg-fju-red/10"><i class="fas fa-trash"></i></button></div></div>').join('')}
function filterAct(f){document.querySelectorAll('.act-f').forEach(b=>{b.classList.remove('bg-fju-blue','text-white');b.classList.add('bg-gray-100','text-gray-500')});document.querySelector('.act-f[data-f="'+f+'"]')?.classList.add('bg-fju-blue','text-white');document.querySelector('.act-f[data-f="'+f+'"]')?.classList.remove('bg-gray-100','text-gray-500');renderActs(f==='all'?allActs:allActs.filter(a=>a.status===f))}
function addAct(){fetch('/api/activities',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({title:document.getElementById('a-title').value,description:document.getElementById('a-desc').value,event_date:document.getElementById('a-date').value,start_time:'09:00',end_time:'17:00',max_participants:parseInt(document.getElementById('a-max').value)||50,category:'academic'})}).then(r=>r.json()).then(()=>{document.getElementById('act-modal').classList.add('hidden');location.reload()})}
function registerAct(id){fetch('/api/activities/'+id+'/register',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({user_id:1})}).then(r=>r.json()).then(res=>alert(res.message))}
function deleteAct(id){if(!confirm('確定刪除？'))return;fetch('/api/activities/'+id,{method:'DELETE',headers:{'Accept':'application/json'}}).then(()=>location.reload())}
</script>
@endsection
