@extends('layouts.shell')
@section('title', '行事曆')
@php $activePage = 'calendar'; @endphp
@section('content')
<div class="space-y-6">
  <div class="flex items-center justify-between"><h2 class="font-bold text-fju-blue text-lg"><i class="fas fa-calendar-alt mr-2 text-fju-yellow"></i>校園行事曆</h2><button onclick="document.getElementById('event-modal').classList.remove('hidden')" class="btn-yellow px-4 py-2 text-sm"><i class="fas fa-plus mr-1"></i>新增事件</button></div>
  <div class="bg-white rounded-fju-lg p-6 shadow-sm border border-gray-100"><div id="evo-calendar"></div></div>
  <div class="bg-white rounded-fju-lg shadow-sm border border-gray-100 overflow-hidden"><div class="px-5 py-3 border-b border-gray-100"><h3 class="font-bold text-fju-blue text-sm"><i class="fas fa-list mr-2 text-fju-yellow"></i>近期活動</h3></div><div id="event-list"><div class="p-4 text-center text-gray-400"><i class="fas fa-spinner fa-spin"></i></div></div></div>
  <div id="event-modal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center"><div class="bg-white rounded-fju-lg p-6 w-full max-w-md mx-4"><h3 class="font-bold text-fju-blue text-lg mb-4"><i class="fas fa-calendar-plus mr-2 text-fju-yellow"></i>新增行事曆事件</h3><div class="space-y-3"><div><label class="text-xs text-gray-400">標題</label><input id="ev-title" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm" required></div><div><label class="text-xs text-gray-400">日期</label><input type="date" id="ev-date" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm" required></div><div><label class="text-xs text-gray-400">類型</label><select id="ev-type" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm"><option>meeting</option><option>competition</option><option>performance</option><option>workshop</option><option>service</option><option>sports</option></select></div><div><label class="text-xs text-gray-400">說明</label><textarea id="ev-desc" rows="2" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm"></textarea></div></div><div class="flex gap-2 mt-4"><button onclick="addEvent()" class="flex-1 btn-yellow py-2"><i class="fas fa-check mr-1"></i>新增</button><button onclick="document.getElementById('event-modal').classList.add('hidden')" class="flex-1 py-2 rounded-fju border border-gray-200 text-sm text-gray-500">取消</button></div></div></div>
</div>
<script>
fetch('/api/calendar/events').then(r=>r.json()).then(res=>{const events=res.data;
document.getElementById('event-list').innerHTML='<table class="w-full text-sm"><tbody>'+events.map(e=>'<tr class="border-t border-gray-50 hover:bg-gray-50"><td class="p-3"><span class="w-3 h-3 rounded-full inline-block mr-2" style="background:'+e.color+'"></span></td><td class="p-3 font-medium text-fju-blue">'+e.title+'</td><td class="p-3 text-xs text-gray-400">'+e.date+'</td><td class="p-3 text-xs text-gray-400">'+(e.venue||'')+'</td><td class="p-3"><button onclick="deleteEvent('+e.id+')" class="text-fju-red text-xs"><i class="fas fa-trash"></i></button></td></tr>').join('')+'</tbody></table>';
try{$('#evo-calendar').evoCalendar({theme:'Royal Navy',calendarEvents:events.map(e=>({id:e.id,name:e.title,date:e.date,color:e.color,description:e.description||''}))});}catch(e){}});
function addEvent(){const d={title:document.getElementById('ev-title').value,date:document.getElementById('ev-date').value,type:document.getElementById('ev-type').value,description:document.getElementById('ev-desc').value,color:'#003153'};fetch('/api/calendar/events',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(d)}).then(r=>r.json()).then(()=>{document.getElementById('event-modal').classList.add('hidden');location.reload()})}
function deleteEvent(id){if(!confirm('確定刪除？'))return;fetch('/api/calendar/events/'+id,{method:'DELETE',headers:{'Accept':'application/json'}}).then(()=>location.reload())}
</script>
@endsection
