@extends('layouts.shell')
@section('title', '社團資訊')
@php $activePage = 'club-info'; @endphp
@section('content')
<div class="space-y-6">
  <div class="flex items-center justify-between flex-wrap gap-2"><h2 class="font-bold text-fju-blue text-lg"><i class="fas fa-users mr-2 text-fju-yellow"></i>114 學年度社團資訊</h2><div class="flex gap-2"><input id="club-search" oninput="searchClubs()" placeholder="搜尋社團..." class="px-4 py-2 rounded-fju border border-gray-200 text-sm w-48"><button onclick="document.getElementById('club-modal').classList.remove('hidden')" class="btn-yellow px-4 py-2 text-sm"><i class="fas fa-plus mr-1"></i>新增社團</button></div></div>
  <div class="grid grid-cols-2 lg:grid-cols-4 gap-4" id="club-stats"></div>
  <div class="flex gap-2 flex-wrap" id="cat-filters"></div>
  <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4" id="club-grid"><div class="p-8 text-center text-gray-400 col-span-3"><i class="fas fa-spinner fa-spin"></i> 載入中...</div></div>
  <div id="club-modal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center"><div class="bg-white rounded-fju-lg p-6 w-full max-w-md mx-4"><h3 class="font-bold text-fju-blue text-lg mb-4">新增社團</h3><div class="space-y-3"><input id="cl-name" placeholder="社團名稱" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm"><select id="cl-cat" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm"><option value="academic">學藝</option><option value="recreation">康樂</option><option value="sports">體育</option><option value="arts">藝術</option><option value="service">服務</option></select><textarea id="cl-desc" placeholder="描述" class="w-full px-4 py-2 rounded-fju border border-gray-200 text-sm"></textarea></div><div class="flex gap-2 mt-4"><button onclick="addClub()" class="flex-1 btn-yellow py-2"><i class="fas fa-check mr-1"></i>新增</button><button onclick="document.getElementById('club-modal').classList.add('hidden')" class="flex-1 py-2 rounded-fju border border-gray-200 text-sm text-gray-500">取消</button></div></div></div>
</div>
<script>
let allClubs=[];
fetch('/api/clubs').then(r=>r.json()).then(res=>{allClubs=res.data;
  const cats={};allClubs.forEach(c=>{cats[c.category_label]=(cats[c.category_label]||0)+1});
  document.getElementById('club-stats').innerHTML='<div class="bg-white rounded-fju-lg p-4 shadow-sm border border-gray-100 text-center"><div class="text-2xl font-black text-fju-blue">'+allClubs.length+'</div><div class="text-xs text-gray-400">社團總數</div></div><div class="bg-white rounded-fju-lg p-4 shadow-sm border border-gray-100 text-center"><div class="text-2xl font-black text-fju-yellow">'+allClubs.filter(c=>c.type==='club').length+'</div><div class="text-xs text-gray-400">社團</div></div><div class="bg-white rounded-fju-lg p-4 shadow-sm border border-gray-100 text-center"><div class="text-2xl font-black text-fju-green">'+allClubs.filter(c=>c.type==='association').length+'</div><div class="text-xs text-gray-400">學會</div></div><div class="bg-white rounded-fju-lg p-4 shadow-sm border border-gray-100 text-center"><div class="text-2xl font-black text-fju-blue">'+Object.keys(cats).length+'</div><div class="text-xs text-gray-400">分類數</div></div>';
  document.getElementById('cat-filters').innerHTML='<button onclick="filterCat(\'all\')" class="cat-btn px-3 py-1 rounded-fju bg-fju-blue text-white text-xs" data-cat="all">全部</button>'+Object.keys(cats).map(c=>'<button onclick="filterCat(\''+c+'\')" class="cat-btn px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-cat="'+c+'">'+c+' ('+cats[c]+')</button>').join('');
  renderClubs(allClubs)});
function renderClubs(data){document.getElementById('club-grid').innerHTML=data.map(c=>'<div class="bg-white rounded-fju p-4 shadow-sm border border-gray-100 card-hover"><div class="flex items-start justify-between"><div><h3 class="font-bold text-fju-blue text-sm">'+c.name+'</h3><span class="text-[10px] px-2 py-0.5 rounded-full bg-fju-blue/10 text-fju-blue">'+c.category_label+'</span></div><span class="text-xs text-gray-400">'+c.member_count+' 人</span></div><p class="text-xs text-gray-500 mt-2">'+(c.description||'')+'</p><div class="flex gap-1 mt-2"><button onclick="deleteClub('+c.id+')" class="text-fju-red text-xs px-2 py-1 rounded hover:bg-fju-red/10"><i class="fas fa-trash"></i></button></div></div>').join('')}
function searchClubs(){const s=document.getElementById('club-search').value.toLowerCase();renderClubs(allClubs.filter(c=>c.name.toLowerCase().includes(s)))}
function filterCat(cat){document.querySelectorAll('.cat-btn').forEach(b=>{b.classList.remove('bg-fju-blue','text-white');b.classList.add('bg-gray-100','text-gray-500')});document.querySelector('.cat-btn[data-cat="'+cat+'"]')?.classList.add('bg-fju-blue','text-white');document.querySelector('.cat-btn[data-cat="'+cat+'"]')?.classList.remove('bg-gray-100','text-gray-500');renderClubs(cat==='all'?allClubs:allClubs.filter(c=>c.category_label===cat))}
function addClub(){fetch('/api/clubs',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({name:document.getElementById('cl-name').value,category:document.getElementById('cl-cat').value,category_label:document.getElementById('cl-cat').selectedOptions[0].text,description:document.getElementById('cl-desc').value,type:'club',member_count:0,is_active:true})}).then(r=>r.json()).then(()=>{document.getElementById('club-modal').classList.add('hidden');location.reload()})}
function deleteClub(id){if(!confirm('確定刪除？'))return;fetch('/api/clubs/'+id,{method:'DELETE',headers:{'Accept':'application/json'}}).then(()=>location.reload())}
</script>
@endsection
