@extends('layouts.shell')
@section('title', '互動校園分區地圖')
@php $activePage = 'campus-map'; @endphp
@section('content')
<div class="flex gap-4 h-full" style="min-height: calc(100vh - 280px);">
  <div class="w-72 shrink-0 bg-white rounded-fju-lg shadow-sm border border-gray-100 p-4 overflow-y-auto">
    <div class="relative mb-4"><i class="fas fa-search absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-xs"></i><input id="map-search" type="text" placeholder="搜尋建築物..." class="w-full pl-9 pr-3 py-2.5 rounded-fju border border-gray-200 text-sm focus:border-fju-blue outline-none" oninput="filterBuildings()"></div>
    <div class="mb-4"><p class="text-xs text-gray-400 font-bold mb-2">建築類型</p><div class="flex flex-wrap gap-1" id="type-filters"><button onclick="filterType('all')" class="type-btn px-3 py-1 rounded-fju bg-fju-blue text-white text-xs" data-type="all">全部</button><button onclick="filterType('教學')" class="type-btn px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-type="教學">教學</button><button onclick="filterType('行政')" class="type-btn px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-type="行政">行政</button><button onclick="filterType('體育')" class="type-btn px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-type="體育">體育</button><button onclick="filterType('宿舍')" class="type-btn px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-type="宿舍">宿舍</button><button onclick="filterType('餐飲')" class="type-btn px-3 py-1 rounded-fju bg-gray-100 text-gray-500 text-xs" data-type="餐飲">餐飲</button></div></div>
    <div id="building-list" class="space-y-1"></div>
  </div>
  <div class="flex-1 bg-white rounded-fju-lg shadow-sm border border-gray-100 overflow-hidden"><div id="campus-map-full" style="height: 100%; min-height: 600px;"></div></div>
</div>
<script>
(function(){const map=L.map('campus-map-full',{center:[25.036,121.432],zoom:17,zoomControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20}).addTo(map);
const buildings=[{name:'淨心堂',pos:[25.0363,121.4318],college:'宗教',type:'教學',c:'#DAA520'},{name:'中美堂',pos:[25.0356,121.43],college:'學務處',type:'體育',c:'#00B894',cap:500},{name:'活動中心',pos:[25.0348,121.4305],college:'學務處',type:'行政',c:'#DAA520',cap:200},{name:'羅耀拉大樓',pos:[25.0358,121.433],college:'管理學院',type:'教學',c:'#8E44AD'},{name:'利瑪竇大樓',pos:[25.0372,121.4325],college:'文學院',type:'教學',c:'#E67E22'},{name:'聖言樓',pos:[25.0355,121.431],college:'外語學院',type:'教學',c:'#2980B9'},{name:'伯達樓',pos:[25.0368,121.4335],college:'理工學院',type:'教學',c:'#27AE60'},{name:'濟時樓',pos:[25.035,121.4325],college:'法律學院',type:'行政',c:'#C0392B'},{name:'國璽樓',pos:[25.0345,121.4315],college:'醫學院',type:'教學',c:'#E74C3C'},{name:'醫學大樓',pos:[25.0375,121.434],college:'醫學院',type:'教學',c:'#E74C3C'},{name:'體育館',pos:[25.034,121.432],college:'體育室',type:'體育',c:'#00B894',cap:800},{name:'SF 134',pos:[25.0365,121.4345],college:'理工學院',type:'教學',c:'#27AE60',cap:80},{name:'焯炤館',pos:[25.0352,121.4335],college:'圖書資訊',type:'行政',c:'#003153'},{name:'百鍊廳',pos:[25.0345,121.4325],college:'體育室',type:'體育',c:'#00B894',cap:100},{name:'舒德樓',pos:[25.038,121.432],college:'社科院',type:'教學',c:'#16A085'},{name:'野聲樓',pos:[25.0378,121.431],college:'教育學院',type:'教學',c:'#F39C12'},{name:'輔園餐廳',pos:[25.0347,121.4328],college:'餐飲',type:'餐飲',c:'#FF6B35'},{name:'理園餐廳',pos:[25.0362,121.4348],college:'餐飲',type:'餐飲',c:'#FF6B35'},{name:'宜聖宿舍',pos:[25.038,121.4345],college:'宿舍',type:'宿舍',c:'#7F8C8D'},{name:'立言宿舍',pos:[25.0382,121.4335],college:'宿舍',type:'宿舍',c:'#7F8C8D'}];
window._bData=[];
buildings.forEach(b=>{const m=L.circleMarker(b.pos,{radius:10,fillColor:b.c,color:'#fff',weight:2,fillOpacity:0.85});const cap=b.cap?'<div class="popup-row"><i class="fas fa-users"></i><span>容量：'+b.cap+' 人</span></div>':'';m.bindPopup('<div class="popup-header">'+b.name+'</div><div class="popup-body"><div class="popup-row"><i class="fas fa-school"></i><span>'+b.college+'</span></div>'+cap+'<a href="/module/venue-booking?role={{ $role }}" class="popup-btn"><i class="fas fa-calendar-plus mr-1"></i>我要預約</a> <a href="#" class="popup-btn" style="background:#003153;color:#fff" onclick="map.flyTo(['+b.pos+'],19)"><i class="fas fa-crosshairs mr-1"></i>定位</a></div>',{className:'fju-popup'});m.addTo(map);window._bData.push({...b,marker:m})});
// Build sidebar list
function renderList(data){document.getElementById('building-list').innerHTML=data.map(b=>'<div class="flex items-center gap-2 p-2 rounded-fju hover:bg-fju-bg cursor-pointer transition-all" onclick="map.flyTo(['+b.pos+'],19);window._bData.find(x=>x.name===\''+b.name+'\').marker.openPopup()"><div class="w-3 h-3 rounded-full" style="background:'+b.c+'"></div><div><div class="text-xs font-bold text-fju-blue">'+b.name+'</div><div class="text-[10px] text-gray-400">'+b.college+'</div></div></div>').join('')}
renderList(buildings);
window.filterBuildings=function(){const s=document.getElementById('map-search').value.toLowerCase();const f=window._bData.filter(b=>b.name.toLowerCase().includes(s)||b.college.toLowerCase().includes(s));renderList(f);window._bData.forEach(b=>{if(f.includes(b))map.addLayer(b.marker);else map.removeLayer(b.marker)})};
window.filterType=function(t){document.querySelectorAll('.type-btn').forEach(b=>{b.classList.remove('bg-fju-blue','text-white');b.classList.add('bg-gray-100','text-gray-500')});document.querySelector('.type-btn[data-type="'+t+'"]').classList.add('bg-fju-blue','text-white');document.querySelector('.type-btn[data-type="'+t+'"]').classList.remove('bg-gray-100','text-gray-500');const f=t==='all'?window._bData:window._bData.filter(b=>b.type===t);renderList(f);window._bData.forEach(b=>{if(f.includes(b))map.addLayer(b.marker);else map.removeLayer(b.marker)})};
window.map=map})();
</script>
@endsection
